// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';

//@ts-expect-error
import type { StoryblokRichtext, StoryblokAsset } from './storyblok.d.ts';
export interface Blog {
  title?: string;
  subtitle?: string;
  content?: StoryblokRichtext;
  component: "blog";
  _uid: string;
  [k: string]: unknown;
}

export interface FeaturedBlogs {
  title?: string;
  blogs?: (ISbStoryData<Blog> | string)[];
  component: "featuredBlogs";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (Blog | FeaturedBlogs | Page | Project | ProjectList)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Project {
  title?: string;
  subtitle?: string;
  image?: StoryblokAsset;
  content?: StoryblokRichtext;
  component: "project";
  _uid: string;
  [k: string]: unknown;
}

export interface ProjectList {
  title?: string;
  projects?: (ISbStoryData<Project> | string)[];
  component: "projectList";
  _uid: string;
  [k: string]: unknown;
}
