// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
//@ts-expect-error
import type { StoryblokAsset, StoryblokRichtext } from './storyblok.d.ts';
export interface Experience {
  title?: string;
  subtitle?: string;
  time?: string;
  content?: StoryblokRichtext;
  skills?: {value: string[]};
  component: "experience";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (Experience | Page | Project | ProjectList)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Project {
  title?: string;
  subtitle?: string;
  image?: StoryblokAsset;
  content?: StoryblokRichtext;
  component: "project";
  _uid: string;
  [k: string]: unknown;
}

export interface ProjectList {
  title?: string;
  projects?: (ISbStoryData<Project> | string)[];
  component: "projectList";
  _uid: string;
  [k: string]: unknown;
}
