// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokRichtext } from './storyblok.d.ts';

export interface Blog {
  title?: string;
  subtitle?: string;
  content?: StoryblokRichtext;
  component: "blog";
  _uid: string;
  [k: string]: unknown;
}

export interface FeaturedBlogs {
  title?: string;
  blogs?: (ISbStoryData<Blog> | string)[];
  component: "featuredBlogs";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (Blog | FeaturedBlogs | Page)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}
